#pragma once

#define WINDOW_WIDTH 600
#define WINDOW_HEIGHT 480

#define FPS 60

#define CAR_HEIGHT 100
#define CAR_WIDTH 50

#define ROAD_WIDTH_1 200
#define ROAD_WIDTH_2 100

#define MAP_LENGHT 5760

#define MAP_SECTIONS_NUMBER 4

#define CHECKPOINT_DISTANCE 3000;

#define LEAD_IN_TIME 30

#define STARTER_LIVES 5

#define MENU_TOP_WIDTH WINDOW_WIDTH
#define MENU_TOP_HEIGHT 24
#define MENU_TOP_X 0
#define MENU_TOP_Y 0

#define MENU_BOTTOM_WIDTH WINDOW_WIDTH
#define MENU_BOTTOM_HEIGHT 24
#define MENU_BOTTOM_X 0
#define MENU_BOTTOM_Y WINDOW_HEIGHT - MENU_BOTTOM_HEIGHT

#define PAUSE_MENU_A_WIDTH 56
#define PAUSE_MENU_A_HEIGHT 24
#define PAUSE_MENU_A_X WINDOW_WIDTH/2 - PAUSE_MENU_A_WIDTH/2
#define PAUSE_MENU_A_Y 100

#define PAUSE_MENU_B_WIDTH 150
#define PAUSE_MENU_B_HEIGHT 24
#define PAUSE_MENU_B_X WINDOW_WIDTH/2 - PAUSE_MENU_B_WIDTH/2
#define PAUSE_MENU_B_Y PAUSE_MENU_A_Y + 40

#define OVER_MENU_A_WIDTH 96
#define OVER_MENU_A_HEIGHT 24
#define OVER_MENU_A_X WINDOW_WIDTH/2 - OVER_MENU_A_WIDTH/2
#define OVER_MENU_A_Y 120

#define OVER_MENU_B_WIDTH 120
#define OVER_MENU_B_HEIGHT 24
#define OVER_MENU_B_X WINDOW_WIDTH/2 - OVER_MENU_B_WIDTH/2
#define OVER_MENU_B_Y OVER_MENU_A_Y + 80